import 'package:u/utilities.dart';

import '../theme.dart';

abstract class AppNavigator {
  static void snackbar({
    required final String title,
    required final String subtitle,
    final Color? backgroundColor,
    final Color colorText = Colors.white,
    final int duration = 3,
    final SnackPosition? snackPosition,
    final Widget? titleText,
    final Widget? messageText,
    final Widget? icon,
    final bool? shouldIconPulse,
    final double? maxWidth,
    final EdgeInsets? margin,
    final EdgeInsets? padding,
    final double? borderRadius,
    final Color? borderColor,
    final double? borderWidth,
    final Color? leftBarIndicatorColor,
    final List<BoxShadow>? boxShadows,
    final Gradient? backgroundGradient,
    final TextButton? mainButton,
    final OnTap? onTap,
    final bool? isDismissible,
    final bool? showProgressIndicator,
    final DismissDirection? dismissDirection,
    final AnimationController? progressIndicatorController,
    final Color? progressIndicatorBackgroundColor,
    final Animation<Color>? progressIndicatorValueColor,
    final SnackStyle? snackStyle,
    final Curve? forwardAnimationCurve,
    final Curve? reverseAnimationCurve,
    final Duration? animationDuration,
    final double? barBlur,
    final double? overlayBlur,
    final SnackbarStatusCallback? snackbarStatus,
    final Color? overlayColor,
    final Form? userInputForm,
    final bool instantInit = true,
  }) {
    delay(100, () {
      Get.snackbar(
        title,
        subtitle,
        backgroundColor: backgroundColor ?? Colors.grey.shade700,
        colorText: colorText,
        maxWidth: maxWidth,
        onTap: onTap,
        margin: margin,
        borderRadius: borderRadius,
        snackPosition: snackPosition,
        padding: padding,
        animationDuration: animationDuration,
        backgroundGradient: backgroundGradient,
        barBlur: barBlur,
        borderColor: borderColor,
        borderWidth: borderWidth,
        boxShadows: boxShadows,
        dismissDirection: dismissDirection,
        duration: Duration(seconds: duration),
        forwardAnimationCurve: forwardAnimationCurve,
        icon: icon,
        instantInit: instantInit,
        isDismissible: isDismissible,
        leftBarIndicatorColor: leftBarIndicatorColor,
        mainButton: mainButton,
        messageText: messageText,
        overlayBlur: overlayBlur,
        overlayColor: overlayColor,
        progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
        progressIndicatorController: progressIndicatorController,
        progressIndicatorValueColor: progressIndicatorValueColor,
        reverseAnimationCurve: reverseAnimationCurve,
        shouldIconPulse: shouldIconPulse,
        showProgressIndicator: showProgressIndicator,
        snackbarStatus: snackbarStatus,
        snackStyle: snackStyle,
        titleText: titleText,
        userInputForm: userInputForm,
      );
    });
  }

  static void snackbarGreen({
    required final String title,
    required final String subtitle,
    final Color backgroundColor = AppColors.green,
    final Color colorText = Colors.white,
    final int duration = 3,
    final SnackPosition? snackPosition,
    final Widget? titleText,
    final Widget? messageText,
    final Widget? icon,
    final bool? shouldIconPulse,
    final double? maxWidth,
    final EdgeInsets? margin,
    final EdgeInsets? padding,
    final double? borderRadius,
    final Color? borderColor,
    final double? borderWidth,
    final Color? leftBarIndicatorColor,
    final List<BoxShadow>? boxShadows,
    final Gradient? backgroundGradient,
    final TextButton? mainButton,
    final OnTap? onTap,
    final bool? isDismissible,
    final bool? showProgressIndicator,
    final DismissDirection? dismissDirection,
    final AnimationController? progressIndicatorController,
    final Color? progressIndicatorBackgroundColor,
    final Animation<Color>? progressIndicatorValueColor,
    final SnackStyle? snackStyle,
    final Curve? forwardAnimationCurve,
    final Curve? reverseAnimationCurve,
    final Duration? animationDuration,
    final double? barBlur,
    final double? overlayBlur,
    final SnackbarStatusCallback? snackbarStatus,
    final Color? overlayColor,
    final Form? userInputForm,
    final bool instantInit = true,
  }) {
    delay(100, () {
      Get.snackbar(
      title,
      subtitle,
      backgroundColor: backgroundColor,
      colorText: colorText,
      maxWidth: maxWidth,
      onTap: onTap,
      margin: margin,
      borderRadius: borderRadius,
      snackPosition: snackPosition,
      padding: padding,
      animationDuration: animationDuration,
      backgroundGradient: backgroundGradient,
      barBlur: barBlur,
      borderColor: borderColor,
      borderWidth: borderWidth,
      boxShadows: boxShadows,
      dismissDirection: dismissDirection,
      duration: Duration(seconds: duration),
      forwardAnimationCurve: forwardAnimationCurve,
      icon: icon,
      instantInit: instantInit,
      isDismissible: isDismissible,
      leftBarIndicatorColor: leftBarIndicatorColor,
      mainButton: mainButton,
      messageText: messageText,
      overlayBlur: overlayBlur,
      overlayColor: overlayColor,
      progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
      progressIndicatorController: progressIndicatorController,
      progressIndicatorValueColor: progressIndicatorValueColor,
      reverseAnimationCurve: reverseAnimationCurve,
      shouldIconPulse: shouldIconPulse,
      showProgressIndicator: showProgressIndicator,
      snackbarStatus: snackbarStatus,
      snackStyle: snackStyle,
      titleText: titleText,
      userInputForm: userInputForm,
    );
    });
  }

  static void snackbarRed({
    required final String title,
    required final String subtitle,
    final Color backgroundColor = AppColors.red,
    final Color colorText = Colors.white,
    final int duration = 3,
    final SnackPosition? snackPosition,
    final Widget? titleText,
    final Widget? messageText,
    final Widget? icon,
    final bool? shouldIconPulse,
    final double? maxWidth,
    final EdgeInsets? margin,
    final EdgeInsets? padding,
    final double? borderRadius,
    final Color? borderColor,
    final double? borderWidth,
    final Color? leftBarIndicatorColor,
    final List<BoxShadow>? boxShadows,
    final Gradient? backgroundGradient,
    final TextButton? mainButton,
    final OnTap? onTap,
    final bool? isDismissible,
    final bool? showProgressIndicator,
    final DismissDirection? dismissDirection,
    final AnimationController? progressIndicatorController,
    final Color? progressIndicatorBackgroundColor,
    final Animation<Color>? progressIndicatorValueColor,
    final SnackStyle? snackStyle,
    final Curve? forwardAnimationCurve,
    final Curve? reverseAnimationCurve,
    final Duration? animationDuration,
    final double? barBlur,
    final double? overlayBlur,
    final SnackbarStatusCallback? snackbarStatus,
    final Color? overlayColor,
    final Form? userInputForm,
    final bool instantInit = true,
  }) {
    delay(100, () {
      Get.snackbar(
        title,
        subtitle,
        backgroundColor: backgroundColor,
        colorText: colorText,
        maxWidth: maxWidth,
        onTap: onTap,
        margin: margin,
        borderRadius: borderRadius,
        snackPosition: snackPosition,
        padding: padding,
        animationDuration: animationDuration,
        backgroundGradient: backgroundGradient,
        barBlur: barBlur,
        borderColor: borderColor,
        borderWidth: borderWidth,
        boxShadows: boxShadows,
        dismissDirection: dismissDirection,
        duration: Duration(seconds: duration),
        forwardAnimationCurve: forwardAnimationCurve,
        icon: icon,
        instantInit: instantInit,
        isDismissible: isDismissible,
        leftBarIndicatorColor: leftBarIndicatorColor,
        mainButton: mainButton,
        messageText: messageText,
        overlayBlur: overlayBlur,
        overlayColor: overlayColor,
        progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
        progressIndicatorController: progressIndicatorController,
        progressIndicatorValueColor: progressIndicatorValueColor,
        reverseAnimationCurve: reverseAnimationCurve,
        shouldIconPulse: shouldIconPulse,
        showProgressIndicator: showProgressIndicator,
        snackbarStatus: snackbarStatus,
        snackStyle: snackStyle,
        titleText: titleText,
        userInputForm: userInputForm,
      );
    });
  }

  static void snackbarOrange({
    required final String title,
    required final String subtitle,
    final Color backgroundColor = AppColors.orange,
    final Color colorText = Colors.white,
    final int duration = 3,
    final SnackPosition? snackPosition,
    final Widget? titleText,
    final Widget? messageText,
    final Widget? icon,
    final bool? shouldIconPulse,
    final double? maxWidth,
    final EdgeInsets? margin,
    final EdgeInsets? padding,
    final double? borderRadius,
    final Color? borderColor,
    final double? borderWidth,
    final Color? leftBarIndicatorColor,
    final List<BoxShadow>? boxShadows,
    final Gradient? backgroundGradient,
    final TextButton? mainButton,
    final OnTap? onTap,
    final bool? isDismissible,
    final bool? showProgressIndicator,
    final DismissDirection? dismissDirection,
    final AnimationController? progressIndicatorController,
    final Color? progressIndicatorBackgroundColor,
    final Animation<Color>? progressIndicatorValueColor,
    final SnackStyle? snackStyle,
    final Curve? forwardAnimationCurve,
    final Curve? reverseAnimationCurve,
    final Duration? animationDuration,
    final double? barBlur,
    final double? overlayBlur,
    final SnackbarStatusCallback? snackbarStatus,
    final Color? overlayColor,
    final Form? userInputForm,
    final bool instantInit = true,
  }) {
    delay(100, () {
      Get.snackbar(
      title,
      subtitle,
      backgroundColor: backgroundColor,
      colorText: colorText,
      maxWidth: maxWidth,
      onTap: onTap,
      margin: margin,
      borderRadius: borderRadius,
      snackPosition: snackPosition,
      padding: padding,
      animationDuration: animationDuration,
      backgroundGradient: backgroundGradient,
      barBlur: barBlur,
      borderColor: borderColor,
      borderWidth: borderWidth,
      boxShadows: boxShadows,
      dismissDirection: dismissDirection,
      duration: Duration(seconds: duration),
      forwardAnimationCurve: forwardAnimationCurve,
      icon: icon,
      instantInit: instantInit,
      isDismissible: isDismissible,
      leftBarIndicatorColor: leftBarIndicatorColor,
      mainButton: mainButton,
      messageText: messageText,
      overlayBlur: overlayBlur,
      overlayColor: overlayColor,
      progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
      progressIndicatorController: progressIndicatorController,
      progressIndicatorValueColor: progressIndicatorValueColor,
      reverseAnimationCurve: reverseAnimationCurve,
      shouldIconPulse: shouldIconPulse,
      showProgressIndicator: showProgressIndicator,
      snackbarStatus: snackbarStatus,
      snackStyle: snackStyle,
      titleText: titleText,
      userInputForm: userInputForm,
    );
    });
  }
}
